#Je créé ce fichier pour configurer SpringBoot

#Ici je peux par exemple changer le port par défaut du serveur
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mpam
    username: postgres
    password: password
    #Si je met web aplication sur none, je désactive le server
    #Par défaut c'est servlet

  main:
    web-application-type: servlet
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
